# Generated by Django 6.1.1 on 2026-09-07 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_programme'),
        ('users', '0004_lecturerprofile_studentprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='lecturer',
        ),
        migrations.AddField(
            model_name='course',
            name='lecturer',
            field=models.ManyToManyField(null=True, related_name='courses', to='users.lecturerprofile'),
        ),
    ]
