# Generated by Django 6.1.1 on 2026-09-25 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0002_academicyear"),
        ("courses", "0007_remove_course_lecturer_course_lecturer"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="academic_year",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="academic_year",
                to="academics.academicyear",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="course",
            name="semester",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
