# Generated by Django 6.1.1 on 2026-09-24 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="grade",
            name="marks",
        ),
        migrations.AddField(
            model_name="grade",
            name="assignment_marks",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name="grade",
            name="cat_marks",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name="grade",
            name="exam_marks",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
        migrations.AddField(
            model_name="grade",
            name="total_marks",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
