# Generated by Django 6.1.1 on 2026-09-25 13:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0002_academicyear"),
        ("assessment", "0002_remove_grade_marks_grade_assignment_marks_and_more"),
        ("courses", "0007_remove_course_lecturer_course_lecturer"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="grade",
            name="assignment_marks",
        ),
        migrations.RemoveField(
            model_name="grade",
            name="cat_marks",
        ),
        migrations.RemoveField(
            model_name="grade",
            name="exam_marks",
        ),
        migrations.RemoveField(
            model_name="grade",
            name="total_marks",
        ),
        migrations.AddField(
            model_name="grade",
            name="marks",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="assessment",
            name="assessment_type",
            field=models.CharField(
                choices=[
                    ("CAT", "CAT"),
                    ("ASSIGNMENT", "Assignment"),
                    ("EXAM", "Exam"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Performance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_marks",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "grade",
                    models.CharField(
                        choices=[
                            ("A", "A"),
                            ("B", "B"),
                            ("C", "C"),
                            ("D", "D"),
                            ("F", "F"),
                            ("I", "Incomplete"),
                        ],
                        default="I",
                        max_length=1,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="performances",
                        to="academics.academicyear",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="performances",
                        to="courses.course",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="performances",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("student", "course", "academic_year"),
                        name="unique_student_course_academic_year",
                    )
                ],
            },
        ),
    ]
